added quality gate

diff --git a/.github/workflows/workflow.yml b/.github/workflows/workflow.yml
--- a/.github/workflows/workflow.yml
+++ b/.github/workflows/workflow.yml
@@ -20,28 +20,12 @@ jobs:
         env:
           GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
           SONAR_TOKEN: ${{ secrets.SONARCLOUD_TOKEN }}
+      - name: Check SonarCloud Quality Gate
+        run: |
+          TASK_ID=$(curl -s -u "${{ secrets.SONARCLOUD_TOKEN }}:" "https://sonarcloud.io/api/ce/activity" | jq -r '.[0].analysisId')
+          QG_STATUS=$(curl -s -u "${{ secrets.SONARCLOUD_TOKEN }}:" "https://sonarcloud.io/api/qualitygates/project_status?analysisId=${TASK_ID}" | jq -r '.projectStatus.status')
 
-#      - name: OWASP ZAP
-#        uses: zaproxy/action-baseline@v0.8.0
-#        with:
-#          # Target URL
-#          target: "http://localhost:4000"
-#          fail_action: false
-#          token: $
-#          issue_title: Security Tests
-
-      # Check the Quality Gate status.
-      - name: SonarQube Quality Gate check
-        id: sonarqube-quality-gate-check
-        uses: sonarsource/sonarqube-quality-gate-action@master
-        # Force to fail step after specific time.
-        timeout-minutes: 5
-        env:
-        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
-        SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }} #OPTIONAL
-
-      # Optionally you can use the output from the Quality Gate in another step.
-      # The possible outputs of the `quality-gate-status` variable are `PASSED`, `WARN` or `FAILED`.
-      - name: "Example show SonarQube Quality Gate Status value"
-        run: echo "The Quality Gate status is ${{ steps.sonarqube-quality-gate-check.outputs.quality-gate-status }}"
-
+          if [ "${QG_STATUS}" = "ERROR" ]; then
+              echo "Quality Gate failed. Stopping the pipeline."
+              exit 1
+          fi
